# Generated by Django 4.2.5 on 2023-09-19 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('surname', models.CharField(blank=True, max_length=255, null=True)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_birth', models.DateTimeField(blank=True, null=True)),
                ('job', models.CharField(blank=True, max_length=255, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv_of_workers/')),
                ('time_job', models.CharField(blank=True, max_length=50000, null=True)),
                ('place', models.CharField(blank=True, max_length=500000, null=True)),
                ('username', models.CharField(blank=True, max_length=500, null=True)),
                ('password', models.CharField(blank=True, max_length=500, null=True)),
                ('count_news', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('job_category', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.CharField(blank=True, max_length=500000, null=True)),
                ('field', models.FileField(blank=True, null=True, upload_to='fields/')),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_reclama', models.BooleanField(blank=True, default=False, null=True)),
                ('place', models.CharField(blank=True, choices=[('Toshkent', 'Toshkent'), ('Navoiy', 'Navoiy'), ('Buxoro', 'Buxoro'), ('Samarqand', 'Samarqand'), ('Xorazm', 'Xorazm'), ('Nukus', 'Nukus'), ("Qoraqalpog'iston", "Qoraqalpog'iston"), ('Jizzax', 'Jizzax'), ('Sirdaryo', 'Sirdaryo'), ('Surxondaryo', 'Surxondaryo'), ('Qashqadaryo', 'Qashqadaryo'), ('Fargona', 'Fargona'), ('Andijon', 'Andijon'), ('Namangan', 'Namangan')], max_length=5000, null=True)),
                ('language', models.CharField(blank=True, choices=[('ozbek', 'ozbek'), ('rus', 'rus'), ('eng', 'eng'), ('uz', 'uz')], default='ozbek', max_length=255)),
                ('category', models.CharField(blank=True, choices=[("O'zbekiston", "O'zbekiston"), ('Dunyo', 'Dunyo'), ('Jamiyat', 'Jamiyat'), ('Madaniyat', 'Madaniyat'), ('Iqtisodiyot', 'Iqtisodiyot'), ('Texno', 'Texno'), ('Sport', 'Sport'), ('Salomatlik', 'Salomatlik')], max_length=5000, null=True)),
                ('creted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsist.admins')),
            ],
        ),
    ]
