# Generated by Django 4.2.5 on 2023-09-19 12:58

from django.db import migrations, models
import newsist.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='field',
            field=models.FileField(blank=True, null=True, upload_to=newsist.models.get_audio_upload),
        ),
    ]
